apiVersion: apps/v1
kind: Deployment
metadata:
  name: archeobot-controller-manager
  namespace: devops-archeobot
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ARTIFACTORY_BASE_DNS
              value: apps.clab.devops.gov.bc.ca
            - name: ARTIFACTORY_URL
              value: https://artifacts.apps.clab.devops.gov.bc.ca
            - name: CLUSTER_NAME
              value: clab
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ANSIBLE_DEBUG_LOGS
              value: "False"
