---
 # tasks file for artifactory project

- set_fact:
    new_quota: "{{ quota_in_gi | default(5) }}"

- name: Set calculated variables
  set_fact:
    project_key: "{{ key | default(gen_key) }}"
    new_quota_in_bytes: "{{ new_quota|int * 1024 * 1024 * 1024 }}"

- name: Check project status
  uri:
    url: "{{ artifactory_url }}/access/api/v1/projects/{{ project_key }}"
    method: GET
    body_format: json
    headers:
      Content-type: "application/json"
      Authorization: "Bearer {{ lookup('file', '{{ admin_token_loc }}') }}"
    status_code: 200,404
  register: current_project_status

- set_fact:
    current_quota: "{{ current_project_status.json.storage_quota_bytes|default(0) / 1024.0 / 1024.0 / 1024.0 }}"

- name: If the relevant approval object doesn't exist, create it.
  include_tasks: "create-approval.yaml"
  when: approval.resources|count == 0

- name: If the ArtProj quota is the same as the current quota, do the status quo tasks.
  include_tasks: "status-quo.yaml"
  when: current_quota|int == new_quota|int

- name: Act on the project (or not) depending on the approval status.
  include_tasks: "{{ approval.resources[0].spec.approval_status|default('pending') }}.yaml"
  when: current_quota|int != new_quota|int


