---
- hosts:        localhost
  gather_facts: no
  vars:
    meta: '{{ ansible_operator_meta }}'
#  collections:
#    - community.kubernetes
#    - operator_sdk.util
  
  tasks:
#    - name: Setup Testing Variables
#      include_vars: ../test/test-vars-artifactoryProject.yml
#      when: meta is undefined
  
    - name: Generate variables
      set_fact:
        artifactory_url: "{{ lookup('env', 'ARTIFACTORY_URL')}}"
        namespace_plate: "{{ meta.namespace | regex_replace('\\-tools$|-dev$|-test$|-prod$', '')}}"
        gen_key: "{{ meta.name | regex_search('^.') }}{{ meta.namespace | regex_search('^...') }}"

    - name: Generate variables
      set_fact:
        project_key: "{{ key | default(gen_key) }}"
        approval: "{{ approved | default(false) }}"

    - name: Set calculated variables
      set_fact:
        admin_pass_loc: "{{ testPass | default('/tmp/ansible-operator/admin/password') }}"
        admin_token_loc: "{{ testToken | default('/tmp/ansible-operator/admin/token') }}"

    - import_role:
        name: "artifactory_project"
      when: approval

    - name: Update CR ArtifactoryProject detail
      k8s:
        state: present
        definition:
          apiVersion: v1alpha1
          kind: ArtifactoryProject
          metadata:
            name: "{{ meta.name }}"
            namespace: "{{ meta.namespace }}"
          spec:
            key: "{{ project_key }}"
            description: "{{ description }}"
            project_admin: "{{ project_admin }}"
            approved: "{{ approval }}"
