---
- hosts:        localhost
  gather_facts: no
  vars:
    meta: '{{ ansible_operator_meta }}'
#  collections:
#    - community.kubernetes
#    - operator_sdk.util
  
  tasks:
    - name: Setup Testing Variables
      include_vars: ../test/test-vars-artifactorySA.yml
      when: meta is undefined

    - name: Set CR Variables
      set_fact:
        admin_pass_loc: "{{ testPass | default('/tmp/ansible-operator/admin/password') }}"
        artifactory_url: "{{ lookup('env', 'ARTIFACTORY_URL')}}"
        project_plate: "{{ meta.namespace | regex_replace('\\-tools$|-dev$|-test$|-prod$', '')}}"
        license_plate: "{{ lookup('password', '/dev/null length=6 chars=ascii_letters') | lower }}"

    - name: Set Art URL and SA name
      set_fact:
        service_account_name: "{{ sa_name | default('{{ meta.name }}-{{ project_plate }}-{{ license_plate }}', true) }}"
        generated_plate: "{{ lookup('password', '/dev/null length=6 chars=ascii_letters') | lower }}"
        plate: "{{ current_plate | default('{{generated_plate}}') }}"
    
    - import_role:
        name: "artifactory_serviceacct"

    - name: Update CR ServiceAccount detail
      k8s:
        state: present
        definition:
          apiVersion: v1alpha1
          kind: ArtifactoryServiceAccount
          metadata:
            name: "{{ meta.name }}"
            namespace: "{{ meta.namespace }}"
          spec:
            sa_name: "{{ service_account_name }}"
            descriptor: "{{ descriptor }}"
            current_plate: "{{ plate }}"
      when: (sa_name is not defined) or (sa_name|length == 0) or (current_plate is not defined) or (current_plate|length == 0)

  
