# permissions for end users to edit artifactoryrepositories.
# NOTE: should only be granted to platform Admin groups for repo creation/management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repo-editor-role
  labels:
    rbac.devops.gov.bc.ca/aggregate-to-art-objects: "true"
rules:
- apiGroups:
  - artifactory.devops.gov.bc.ca
  resources:
  - artifactoryrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - artifactory.devops.gov.bc.ca
  resources:
  - artifactoryrepositories/status
  verbs:
  - get
