---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Operator Cluster RBAC requirements
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
  ##
  ## Rules for artifactory.devops.gov.bc.ca/v1alpha1, Kind: ArtifactoryServiceAccount
  ##
  - apiGroups:
      - artifactory.devops.gov.bc.ca
    resources:
      - artifactoryserviceaccounts
      - artifactoryserviceaccounts/status
      - artifactoryserviceaccounts/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for artifactory.devops.gov.bc.ca/v1alpha1, Kind: ArtifactoryProject
  ##
  - apiGroups:
      - artifactory.devops.gov.bc.ca
    resources:
      - artifactoryprojects
      - artifactoryprojects/status
      - artifactoryprojects/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for artifactory.devops.gov.bc.ca/v1alpha1, Kind: ArtifactoryProjectApproval
  ##
  - apiGroups:
      - artifactory.devops.gov.bc.ca
    resources:
      - artifactoryprojectapprovals
      - artifactoryprojectapprovals/status
      - artifactoryprojectapprovals/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
