# permissions for end users to view artifactoryserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svcacct-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
rules:
- apiGroups:
  - artifactory.devops.gov.bc.ca
  resources:
  - ArtifactoryServiceAccount
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - artifactory.devops.gov.bc.ca
  resources:
  - artifactoryserviceaccounts/status
  verbs:
  - get
