---
# tasks file for artifactory service account
#
# Note: APIs are changing in version 7.49.3+
#   <7.49.3: https://jfrog.com/help/r/jfrog-rest-apis/deprecated-security-apis
#  >=7.49.3: https://jfrog.com/help/r/jfrog-rest-apis/scim-for-users
# Current version, 2024-05: 7.33.12
# ----------------------------------------------------------------------------
- name: Set default params
  set_fact:
    artifactory_user_exists: false
    artifactory_svc_acct_exists: false
    secret_exists: false
    pull_secret_exists: false
    reconciling_msg: []

# Check Artifactory user
# ----------------------
- name: Check for artifactory user
  uri:
    url: "{{ artifactory_url }}/artifactory/api/security/users/{{ service_account_name }}"
    user: "{{ admin_user }}"
    password: "{{ lookup('file', '{{ admin_pass_loc }}') }}"
    method: GET
    body_format: json
    headers:
      Content-type: "application/json"
    force_basic_auth: yes
    status_code: 200,404
  register: artifactory_user_check
- debug:
    msg: "Artifactory user check status: {{ artifactory_user_check.status }}"
- name: Set var for artifactory user
  set_fact:
    artifactory_user_exists: true
  when: artifactory_user_check.status == 200

# Check ArtifactoryServiceAccount
# -------------------------------
- name: Check for ArtifactoryServiceAccount
  k8s_info:
    api_version: v1alpha1
    kind: ArtifactoryServiceAccount
    namespace: "{{ meta.namespace }}"
  register: asa_check
- name: Set var for ArtifactoryServiceAccount
  set_fact:
    artifactory_svc_acct_exists: true
  when: (asa_check.resources is defined) and (asa_check.resources[0].spec is defined)

# Check Secret
# ------------
- name: Check for Secret
  set_fact:
    secret_name: "artifacts-{{ meta.name }}-{{ plate }}"
- k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ secret_name }}"
    namespace: "{{ meta.namespace }}"
  register: secret_check
- set_fact:
    secret_exists: true
  when: (secret_check.resources is defined) and (secret_check.resources[0].data is defined)

# Check pull Secret
# -----------------
- name: Check for pull Secret
  set_fact:
    pull_secret_name: "artifacts-pull-{{ meta.name }}-{{ plate }}"
- k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ pull_secret_name }}"
    namespace: "{{ meta.namespace }}"
  register: pull_secret_check
- set_fact:
    pull_secret_exists: true
  when: (pull_secret_check.resources is defined) and (pull_secret_check.resources[0].data is defined)

# Stop here if all resources exist
# --------------------------------
- block:
  - name: "No Action Required"
    debug:
      msg: "No action required for {{ meta.namespace }}"
  - meta: end_play
  when:
    - artifactory_user_exists
    - artifactory_svc_acct_exists
    - secret_exists
    - pull_secret_exists

# Make a tidy report of what's not in sync
# ----------------------------------------
- set_fact:
    reconciling_start: "Reconciling {{ meta.namespace }}"
- set_fact:
    reconciling_msg: "{{ reconciling_msg + [reconciling_start] }}"
- set_fact:
    reconciling_msg: "{{ reconciling_msg + ['Missing Artifactory user '] }}"
  when: not artifactory_user_exists
- set_fact:
    reconciling_msg: "{{ reconciling_msg + ['Missing ArtifactoryServiceAccount'] }}"
  when: not artifactory_svc_acct_exists
- set_fact:
    reconciling_msg: "{{ reconciling_msg + ['Missing Secret: {{ secret_name }}'] }}"
  when: not secret_exists
- set_fact:
    reconciling_msg: "{{ reconciling_msg + ['Missing pull Secret: {{ pull_secret_name }}'] }}"
  when: not pull_secret_exists
- debug:
    msg: "{{ reconciling_msg }}"

# Testing - don't make any changes, just report what's missing
# ------------------------------------------------------------
#- name: Debug stop
#  debug:
#    msg: "Debug mode, {{ meta.namespace }} not resetting password, stopping"
#- name: Stop
#  ansible.builtin.meta: end_play

# Not all resources are present - generate a password and set all resources
# -------------------------------------------------------------------------
- name: Generate Password
  set_fact:
    generated_password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"

# The Artifactory user API will create or update the user
# -------------------------------------------------------
- name: Set artifactory user
  uri:
    url: "{{ artifactory_url }}/artifactory/api/security/users/{{ service_account_name }}"
    user: "{{ admin_user }}"
    password: "{{ lookup('file', '{{ admin_pass_loc }}') }}"
    method: PUT
    body_format: json
    headers:
      Content-type: "application/json" 
    body: "{{ lookup('template', 'create_account.json.j2') }}"
    force_basic_auth: yes
    status_code: 201

- name: 
  set_fact:
    plate: "{{ asa_check.resources[0].spec.current_plate }}"
  when: asa_check.resources[0].spec.current_plate is defined
- name:
  debug:
    msg: "Using plate {{ plate }} for {{ meta.namespace }}"
- name: Set Secret for Service Account
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "artifacts-{{ meta.name }}-{{ plate }}"
        namespace: "{{ meta.namespace }}"
        labels:
          service: artifactory
      type: kubernetes.io/basic-auth
      data:
        username: "{{ service_account_name | b64encode }}"
        password: "{{ generated_password | b64encode }}"

# Prepare pull secret
# -------------------
- name: Set pull secret variables
  set_fact:
    pull_auth_decode: "{{ service_account_name }}:{{ generated_password }}"
    pull_email: "{{ service_account_name }}@{{ meta.namespace }}.local"
- name: Set encoded pull secret variables
  set_fact:
    pull_auth: "{{ pull_auth_decode | b64encode }}"
- name: Make pull secret json
  set_fact:
    pull_json: '{"auths":{"artifacts.developer.gov.bc.ca":{"username":"{{ service_account_name }}","password":"{{ generated_password }}","email":"{{ pull_email }}","auth":"{{ pull_auth }}"}}}'
- name: Cast pull secret json
  set_fact:
    cast_json: "{{ pull_json | to_json }}"
- name: Set Pull Secret for Service Account
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "artifacts-pull-{{ meta.name }}-{{ plate }}"
        namespace: "{{ meta.namespace }}"
        labels:
          service: artifactory
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ cast_json | b64encode }}"

